cmake_minimum_required(VERSION 3.5)
project(d3d11_hook)

set(CMAKE_PREFIX_PATH ${CMAKE_CURRENT_LIST_DIR}/minhook_debug_x64/lib/minhook)
find_package(minhook)

add_compile_definitions(NOMINMAX)

include_directories(
        ${CMAKE_CURRENT_LIST_DIR}
        ${CMAKE_CURRENT_LIST_DIR}/imgui_d11
        ${CMAKE_CURRENT_LIST_DIR}/tools
        ${CMAKE_CURRENT_LIST_DIR}/game
        ${CMAKE_CURRENT_LIST_DIR}/aimbot
        ${CMAKE_CURRENT_LIST_DIR}/visual
        ${CMAKE_CURRENT_LIST_DIR}/menu
)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_library(${PROJECT_NAME} SHARED
        dll_main.cpp
        tools/memory.cpp
        game/entity.cpp
        aimbot/aimbot.cpp
        visual/visual.cpp
        menu/menu.cpp
        ${CMAKE_CURRENT_LIST_DIR}/imgui_d11/imgui.cpp
        ${CMAKE_CURRENT_LIST_DIR}/imgui_d11/imgui_impl_dx11.cpp
        ${CMAKE_CURRENT_LIST_DIR}/imgui_d11/imgui_impl_win32.cpp
        ${CMAKE_CURRENT_LIST_DIR}/imgui_d11/imgui_draw.cpp
        ${CMAKE_CURRENT_LIST_DIR}/imgui_d11/imgui_tables.cpp
        ${CMAKE_CURRENT_LIST_DIR}/imgui_d11/imgui_widgets.cpp
        tools/console.hpp
        tools/console.cpp
        aimbot/pattern_scan.hpp
)

if (MSVC)
    target_compile_options(${PROJECT_NAME} PRIVATE /utf-8)
endif()

target_link_libraries(${PROJECT_NAME}
        d3d11
        d3dcompiler
        dwmapi
        minhook::minhook
)
